/*
 * File: USART_IT_F302R8_04_USART.c
 *
 * Generated by USART Coder for Xcos with scilab-5.5.2
 * C/C++ source code generated on  :08-Oct-2020
 *
 * Model version      :1.0
 *
 * ******************************************************************************
 * * attention
 * *
 * * THE PRESENT FIRMWARE WHICH IS FOR GUIDANCE ONLY AIMS AT PROVIDING CUSTOMERS
 * * WITH CODING INFORMATION REGARDING THEIR PRODUCTS IN ORDER FOR THEM TO SAVE
 * * TIME. AS A RESULT, STMICROELECTRONICS SHALL NOT BE HELD LIABLE FOR ANY
 * * DIRECT, INDIRECT OR CONSEQUENTIAL DAMAGES WITH RESPECT TO ANY CLAIMS ARISING
 * * FROM THE CONTENT OF SUCH FIRMWARE AND/OR THE USE MADE BY CUSTOMERS OF THE
 * * CODING INFORMATION CONTAINED HEREIN IN CONNECTION WITH THEIR PRODUCTS.
 * *
 * ******************************************************************************
 */
#include "USART_IT_F302R8_04.h"
#include "USART_IT_F302R8_04_USART.h"
extern void** USART_IT_F302R8_04_block_outtbptr; //External array definition of output pointers for blocks 

/*
*******************************************************************************
USART Receive variables definition
*******************************************************************************
*/
struct USART_RxDataLinkTypeDef* G_Usart_RxData;
void*  G_Usart_RxHandler;
struct USART_RxDataLinkTypeDef USART2_RxDataLink;
uint8_t G_USART2_RxDataBuffer[USART2_RX_BUFF_SIZE];

/*
*******************************************************************************
Rx Transfer completed callbacks
Input: UART handle
*******************************************************************************
*/
void HAL_UART_RxCpltCallback(UART_HandleTypeDef *huart)
{
   struct USART_RxDataLinkTypeDef*   pL_UART_RxData = G_Usart_RxData;
   UART_HandleTypeDef*     pL_UART_Handler = (UART_HandleTypeDef*)G_Usart_RxHandler;
   if(pL_UART_Handler == huart)
   {
      pL_UART_RxData->rxStatus = USART_RX_OK;
   }
}

/*
*******************************************************************************
Receive Initialization of USART2
*******************************************************************************
*/
void USART2_Rx_Initialization(void)
{
   G_Usart_RxData = &USART2_RxDataLink;
   G_Usart_RxHandler = (void*)&huart2;
   USART2_RxDataLink.ptRcv = G_USART2_RxDataBuffer;
   USART2_RxDataLink.rxStatus = USART_RX_OFF;
   /* Enable Software Interrupt request*/
   EXTI->IMR |= 1 << 13;
}


void USART_Initialize(void){
   USART_IT_F302R8_04_block_outtbptr[2] = (uint16_t*)&USART2_RxDataLink.nbRcv; //Set first output block pointer
   USART_IT_F302R8_04_block_outtbptr[3] = (uint8_t*)&USART2_RxDataLink.ptRcv; //Set second output block pointer
   USART2_Rx_Initialization(); //Initialize USART2 to receive
}

