/*
 * File: PWM_F401RE_Nucleo.h
 *
 * Generated by STM32 Coder for Xcos with scilab-5.5.2
 * C/C++ source code generated on  :12-Oct-2020
 *
 * Model version      : 1.0
 *
 * ******************************************************************************
 * * attention
 * *
 * * THE PRESENT FIRMWARE WHICH IS FOR GUIDANCE ONLY AIMS AT PROVIDING CUSTOMERS
 * * WITH CODING INFORMATION REGARDING THEIR PRODUCTS IN ORDER FOR THEM TO SAVE
 * * TIME. AS A RESULT, STMICROELECTRONICS SHALL NOT BE HELD LIABLE FOR ANY
 * * DIRECT, INDIRECT OR CONSEQUENTIAL DAMAGES WITH RESPECT TO ANY CLAIMS ARISING
 * * FROM THE CONTENT OF SUCH FIRMWARE AND/OR THE USE MADE BY CUSTOMERS OF THE
 * * CODING INFORMATION CONTAINED HEREIN IN CONNECTION WITH THEIR PRODUCTS.
 * *
 * ******************************************************************************
 */

/* ---- Headers ---- */
#include <string.h> // memcpy

#include "STM32_Config.h"
#include "scicos_block4.h"

/* Time reference */
extern double sci_time;

/* ---- Internals functions declaration ---- */
extern int PWM_F401RE_Nucleo_Initialize(void); //Model initialization function called from main
extern void PWM_F401RE_Nucleo_Step1(void); //Step function called from main


/* external reference declaration */
extern void **work;
extern void **PWM_F401RE_Nucleo_block_outtbptr;
extern scicos_block block_PWM_F401RE_Nucleo;
extern const int size_SCSREAL_N_1x1[];
extern int evoutptr[];
extern void* inptr[];
extern int inszptr[];
extern void* outptr[];
extern int outszptr[];
extern double z[];
extern const double RPAR1[];
extern const int IPAR1[];
/* Dumy variable not used in embedded word but necessary for current version based on PC scicos C functions*/
extern int local_flag;
extern double t; //Simulation time (not used)

#include "PWM_F401RE_Nucleo_TIMER.h" //Include file for TIMER peripheral

