/*
 * File: USART_DMA_F302R8_it.c
 *
 * Generated by STM32 Coder for Xcos with scilab-5.5.2
 * C/C++ source code generated on  :10-Oct-2020
 *
 * Model version      : 1.0
 *
 * ******************************************************************************
 * * attention
 * *
 * * THE PRESENT FIRMWARE WHICH IS FOR GUIDANCE ONLY AIMS AT PROVIDING CUSTOMERS
 * * WITH CODING INFORMATION REGARDING THEIR PRODUCTS IN ORDER FOR THEM TO SAVE
 * * TIME. AS A RESULT, STMICROELECTRONICS SHALL NOT BE HELD LIABLE FOR ANY
 * * DIRECT, INDIRECT OR CONSEQUENTIAL DAMAGES WITH RESPECT TO ANY CLAIMS ARISING
 * * FROM THE CONTENT OF SUCH FIRMWARE AND/OR THE USE MADE BY CUSTOMERS OF THE
 * * CODING INFORMATION CONTAINED HEREIN IN CONNECTION WITH THEIR PRODUCTS.
 * *
 * ******************************************************************************
 */

/* ---- Headers ---- */
#include "USART_DMA_F302R8_it.h"


   /*******************************************************************************
   * Function Name  : EXTI13_Callback
   * Description    : Callback for External Interrupt connected to Pin13
   * Input          : -
   *******************************************************************************/
   void EXTI13_Callback()
   {
    if (*(uint16_t*)USART_DMA_F302R8_block_outtbptr[0] != 0)
    {
     /* Wait for end of current send data*/
     while(USART2_TxDataLink.txStatus == USART_TX_ON);
     /* Copy data to send */
     USART2_CopyDataFcn(*(uint8_t**)USART_DMA_F302R8_block_outtbptr[1], *(uint16_t*)USART_DMA_F302R8_block_outtbptr[0], &USART2_TxDataLink);
    }
    
    if(USART2_TxDataLink.nb2Send)
    {
       USART2_SendDataFcn(&USART2_TxDataLink);
    }
    

   }
