/*
 * File: USART_IT_F302R8_01.c
 *
 * Generated by STM32 Coder for Xcos with scilab-5.5.2
 * C/C++ source code generated on  :05-Oct-2020
 *
 * Model version      : 1.0
 *
 * ******************************************************************************
 * * attention
 * *
 * * THE PRESENT FIRMWARE WHICH IS FOR GUIDANCE ONLY AIMS AT PROVIDING CUSTOMERS
 * * WITH CODING INFORMATION REGARDING THEIR PRODUCTS IN ORDER FOR THEM TO SAVE
 * * TIME. AS A RESULT, STMICROELECTRONICS SHALL NOT BE HELD LIABLE FOR ANY
 * * DIRECT, INDIRECT OR CONSEQUENTIAL DAMAGES WITH RESPECT TO ANY CLAIMS ARISING
 * * FROM THE CONTENT OF SUCH FIRMWARE AND/OR THE USE MADE BY CUSTOMERS OF THE
 * * CODING INFORMATION CONTAINED HEREIN IN CONNECTION WITH THEIR PRODUCTS.
 * *
 * ******************************************************************************
 */

/* ---- Headers ---- */
#include <string.h> // memcpy
#include "STM32_Config.h"

#include "scicos_block4.h"

#include "USART_IT_F302R8_01.h"

double get_scicos_time(void);
void set_scicos_time(double t);
int get_phase_simulation(void);
void assert_sci_failed(const char* e, const char* file, int line){}

 
#define max(a,b) ((a) >= (b) ? (a) : (b))
#define min(a,b) ((a) <= (b) ? (a) : (b))
 
/* Table of constant values passed by ref */
static const int nrd_0 = 0;
static const int nrd_1 = 1;
static const int nrd_10 = 10;
static const int nrd_11 = 11;
static const int nrd_81 = 81;
static const int nrd_82 = 82;
static const int nrd_84 = 84;
static const int nrd_811 = 811;
static const int nrd_812 = 812;
static const int nrd_814 = 814;

/* Some general static variables passed by ref */
static int aaa=0, bbb=0;

/* data shared ptr declaration */
void **work;
void **USART_IT_F302R8_01_block_outtbptr;
scicos_block block_USART_IT_F302R8_01;
/* Dumy variable not used in embedded word but necessary for current version based on PC scicos C functions */
int local_flag=4; //Set to initialization
double t; //Simulation time (not used)

double sci_time;

const int size_SCSREAL_N_1x1[] = {1, 1, SCSREAL_N};

/* def real parameters */
const double RPAR1[ ] = {
/*
 * Routine name of block: evtdly
 * UID of block: 41b3fae6:13d11b95ac2:-7d2e
 * Compiled structure index: 1
 */
5.0000000000000000000000000E-01,

};

const int IPAR1[1] = {0};

/* Initial values */

/* Note that z[]=[z_initial_condition;outtbptr;work]
    z_initial_condition={};
    outtbptr={};
    work= {0,0};
  */

   double z[]={0,0};

  int evoutptr[1];
/*----------------------------------------  Initialization function */
int USART_IT_F302R8_01_Initialize()
{
  int nevprt=1;
  int nport;


  /* Get work ptr of blocks */
  work = (void **)(z+0);

  /* Get outtbptr ptr of blocks */
  USART_IT_F302R8_01_block_outtbptr = (void **)(z+0);

  /* Initialization */

    /* Dumy variable not used in embedded word but necessary for current version based on PC scicos C functions*/
    /* local_flag set to output update */
    local_flag = 1;
    double t; //Simulation time (not used)
return(1);
} //End of function USART_IT_F302R8_01_Initialize()
/*------------------------------  Step1 function called every 1 solver loop(s)*/
void USART_IT_F302R8_01_Step1()
{
  // double t;
  int nevprt=1;
  // int local_flag = 1; //Output update
  int nport;

/*---------------continuous activation state */
/*---------------STM32 block(s) without activation state  */
/*---------------STM32 solver step: NoEvt NoIn NoOut*/
/*---------------STM32 solver step: NoEvt NoIn Out*/
/*---------------STM32 solver step: NoEvt In Out*/
/*---------------STM32 solver step: NoEvt In NoOut*/
/*---------------FLAG: 1  */

  } //End of USART_IT_F302R8_01_Step1 function


double get_scicos_time()
{
  return sci_time;
}

void set_scicos_time(double t)
{
 sci_time = t;
}

int get_phase_simulation()
{
  return 1;
}



void set_block_error(int err)
{
  return;
}

void * scicos_malloc(size_t size)
{
  return malloc(size);
}

void scicos_free(void *p)
{
  free(p);
}

void do_cold_restart()
{
  return;
}

void sciprint (char *fmt)
{
  return;
}

