/*
 * File: TestUsart_GPIO.c
 *
 * Generated by GPIO Coder for Xcos with scilab-5.5.2
 * C/C++ source code generated on  :06-Oct-2020
 *
 * Model version      :1.0
 *
 * ******************************************************************************
 * * attention
 * *
 * * THE PRESENT FIRMWARE WHICH IS FOR GUIDANCE ONLY AIMS AT PROVIDING CUSTOMERS
 * * WITH CODING INFORMATION REGARDING THEIR PRODUCTS IN ORDER FOR THEM TO SAVE
 * * TIME. AS A RESULT, STMICROELECTRONICS SHALL NOT BE HELD LIABLE FOR ANY
 * * DIRECT, INDIRECT OR CONSEQUENTIAL DAMAGES WITH RESPECT TO ANY CLAIMS ARISING
 * * FROM THE CONTENT OF SUCH FIRMWARE AND/OR THE USE MADE BY CUSTOMERS OF THE
 * * CODING INFORMATION CONTAINED HEREIN IN CONNECTION WITH THEIR PRODUCTS.
 * *
 * ******************************************************************************
 */

#include "TestUsart.h"
#include "TestUsart_GPIO.h"

/* Exti function pointer array definition*/
void (*EXTI_Callback[16])(void) = {NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL};
/*******************************************************************************
* Function Name  : HAL_GPIO_EXTI_Callback
* Description    : Callback for External Interrupt
* Input          : GPIO_Pin
*******************************************************************************/
void HAL_GPIO_EXTI_Callback(uint16_t GPIO_Pin)
{
  uint16_t L_PinNum = 0;
  switch(GPIO_Pin) {
    case GPIO_PIN_1 :
      L_PinNum = 1;
    break;
    case GPIO_PIN_2 :
      L_PinNum = 2;
    break;
    case GPIO_PIN_3 :
      L_PinNum = 3;
    break;
    case GPIO_PIN_4 :
      L_PinNum = 4;
    break;
    case GPIO_PIN_5 :
      L_PinNum = 5;
    break;
    case GPIO_PIN_6 :
      L_PinNum = 6;
    break;
    case GPIO_PIN_7 :
      L_PinNum = 7;
    break;
    case GPIO_PIN_8 :
      L_PinNum = 8;
    break;
    case GPIO_PIN_9 :
      L_PinNum = 9;
    break;
    case GPIO_PIN_10 :
      L_PinNum = 10;
    break;
    case GPIO_PIN_11 :
      L_PinNum = 11;
    break;
    case GPIO_PIN_12 :
      L_PinNum = 13;
    break;
    case GPIO_PIN_13 :
      L_PinNum = 13;
    break;
    case GPIO_PIN_14 :
      L_PinNum = 14;
    break;
    case GPIO_PIN_15 :
      L_PinNum = 15;
    break;
    default:
      L_PinNum = 0;
    break;
  }
  if(EXTI_Callback[L_PinNum] != NULL) {
    (*EXTI_Callback[L_PinNum])();
  }
}

void GPIO_Initialize(void){
   EXTI_Callback[13] = EXTI13_Callback; //Set External interrupt callback function for pin 13
}

