/*
 * File: USART_IT_F302R8_06_GPIO.h
 *
 * Generated by GPIO Coder for Xcos with scilab-5.5.2
 * C/C++ source code generated on  :09-Oct-2020
 *
 * Model version      :1.0
 *
 * ******************************************************************************
 * * attention
 * *
 * * THE PRESENT FIRMWARE WHICH IS FOR GUIDANCE ONLY AIMS AT PROVIDING CUSTOMERS
 * * WITH CODING INFORMATION REGARDING THEIR PRODUCTS IN ORDER FOR THEM TO SAVE
 * * TIME. AS A RESULT, STMICROELECTRONICS SHALL NOT BE HELD LIABLE FOR ANY
 * * DIRECT, INDIRECT OR CONSEQUENTIAL DAMAGES WITH RESPECT TO ANY CLAIMS ARISING
 * * FROM THE CONTENT OF SUCH FIRMWARE AND/OR THE USE MADE BY CUSTOMERS OF THE
 * * CODING INFORMATION CONTAINED HEREIN IN CONNECTION WITH THEIR PRODUCTS.
 * *
 * ******************************************************************************
 */

extern void** USART_IT_F302R8_06_block_outtbptr; //External array definition of output pointers for blocks 

extern void (*EXTI_Callback[16])(void); //Exti function pointer array declaration
extern void GPIO_Initialize(void); //GPIO_Exti initialize function
extern void EXTI13_Callback(void);
