/*
 * File: USART_IT_F302R8_03.c
 *
 * Generated by STM32 Coder for Xcos with scilab-5.5.2
 * C/C++ source code generated on  :05-Oct-2020
 *
 * Model version      : 1.0
 *
 * ******************************************************************************
 * * attention
 * *
 * * THE PRESENT FIRMWARE WHICH IS FOR GUIDANCE ONLY AIMS AT PROVIDING CUSTOMERS
 * * WITH CODING INFORMATION REGARDING THEIR PRODUCTS IN ORDER FOR THEM TO SAVE
 * * TIME. AS A RESULT, STMICROELECTRONICS SHALL NOT BE HELD LIABLE FOR ANY
 * * DIRECT, INDIRECT OR CONSEQUENTIAL DAMAGES WITH RESPECT TO ANY CLAIMS ARISING
 * * FROM THE CONTENT OF SUCH FIRMWARE AND/OR THE USE MADE BY CUSTOMERS OF THE
 * * CODING INFORMATION CONTAINED HEREIN IN CONNECTION WITH THEIR PRODUCTS.
 * *
 * ******************************************************************************
 */

/* ---- Headers ---- */
#include <string.h> // memcpy
#include "STM32_Config.h"

#include "scicos_block4.h"

#include "USART_IT_F302R8_03.h"

double get_scicos_time(void);
void set_scicos_time(double t);
int get_phase_simulation(void);
void assert_sci_failed(const char* e, const char* file, int line){}

 
#define max(a,b) ((a) >= (b) ? (a) : (b))
#define min(a,b) ((a) <= (b) ? (a) : (b))
 
/* Table of constant values passed by ref */
static const int nrd_0 = 0;
static const int nrd_1 = 1;
static const int nrd_10 = 10;
static const int nrd_11 = 11;
static const int nrd_81 = 81;
static const int nrd_82 = 82;
static const int nrd_84 = 84;
static const int nrd_811 = 811;
static const int nrd_812 = 812;
static const int nrd_814 = 814;

/* Some general static variables passed by ref */
static int aaa=0, bbb=0;

/* data shared ptr declaration */
void **work;
void **USART_IT_F302R8_03_block_outtbptr;
scicos_block block_USART_IT_F302R8_03;
/* Dumy variable not used in embedded word but necessary for current version based on PC scicos C functions */
int local_flag=4; //Set to initialization
double t; //Simulation time (not used)

double sci_time;

const int size_SCSREAL_N_1x1[] = {1, 1, SCSREAL_N};

/* def real parameters */
const double RPAR1[ ] = {
/*
 * Routine name of block: evtdly
 * UID of block: 41b3fae6:13d11b95ac2:-7d2e
 * Compiled structure index: 1
 */
5.0000000000000000000000000E-01,

};

/* def integer parameters */
const int IPAR1[ ] = {
/*
 * Routine name of block: convert
 * UID of block: -5f95c7d:1566ea22c33:-7f04
 * Compiled structure index: 2
 */
6,

};

/* def object parameters */
/*
 * Routine name of block: cstblk4_m
 * UID of block: -5f95c7d:1566ea22c33:-7ecc
 * Compiled structure index: 3
 */
static float OPAR_1[] = {4};

/* Initial values */

/* Note that z[]=[z_initial_condition;outtbptr;work]
    z_initial_condition={};
    outtbptr={0,0};
    work= {0,0,0,0};
  */

   double z[]={0,0,0,0,0,0};

  int evoutptr[1];
  void* inptr[1];
  int inszptr[3*1];

  void* outptr[1];
  int outszptr[3*1];


  /* outtb declaration */
  unsigned short outtb_2[1]={0};
  float outtb_1[1]={0};

/*----------------------------------------  Initialization function */
int USART_IT_F302R8_03_Initialize()
{
  int nevprt=1;
  int nport;


  /* Get work ptr of blocks */
  work = (void **)(z+2);

  /* Get outtbptr ptr of blocks */
  USART_IT_F302R8_03_block_outtbptr = (void **)(z+0);

  USART_IT_F302R8_03_block_outtbptr[1] = (void *) outtb_2;
  USART_IT_F302R8_03_block_outtbptr[0] = (void *) outtb_1;

  /* Initialization */

  /* Call of 'convert' (type 4 - blk nb 2 - uid ) */
  { 
    /* set blk struc. of 'convert' (type 4 - blk nb 2 - uid ) */
    block_USART_IT_F302R8_03.type   = 4;
    block_USART_IT_F302R8_03.ztyp   = 0;
    block_USART_IT_F302R8_03.ng     = 0;
    block_USART_IT_F302R8_03.nz     = 0;
    block_USART_IT_F302R8_03.noz    = 0;
    block_USART_IT_F302R8_03.nrpar  = 0;
    block_USART_IT_F302R8_03.nopar  = 0;
    block_USART_IT_F302R8_03.nipar  = 1;
    block_USART_IT_F302R8_03.nin    = 1;
    block_USART_IT_F302R8_03.nout   = 1;
    block_USART_IT_F302R8_03.nevout = 0;
    block_USART_IT_F302R8_03.nmode  = 0;
    block_USART_IT_F302R8_03.evout = NULL;
    block_USART_IT_F302R8_03.inptr  = inptr;
    block_USART_IT_F302R8_03.inptr[0]  = USART_IT_F302R8_03_block_outtbptr[0];
    block_USART_IT_F302R8_03.insz = inszptr;
    block_USART_IT_F302R8_03.insz[0]   = 1;
    block_USART_IT_F302R8_03.insz[1]   = 1;
    block_USART_IT_F302R8_03.insz[2]   = SCSREAL_N;
    block_USART_IT_F302R8_03.outptr = outptr;
    block_USART_IT_F302R8_03.outptr[0] = USART_IT_F302R8_03_block_outtbptr[1];
    block_USART_IT_F302R8_03.outsz = outszptr;
    block_USART_IT_F302R8_03.outsz[0]  = 1;
    block_USART_IT_F302R8_03.outsz[1]  = 1;
    block_USART_IT_F302R8_03.outsz[2]  = SCSUINT16_N;
    block_USART_IT_F302R8_03.z = &(z[0]);
    block_USART_IT_F302R8_03.ipar=(int*) &(IPAR1[0]);
    block_USART_IT_F302R8_03.work = (void **)(((double *)work)+1);
  }
  convert(&block_USART_IT_F302R8_03,4);

  /* Call of 'cstblk4_m' (type 4 - blk nb 3 - uid ) */
  { 
    /* set blk struc. of 'cstblk4_m' (type 4 - blk nb 3 - uid ) */
    block_USART_IT_F302R8_03.type   = 4;
    block_USART_IT_F302R8_03.ztyp   = 0;
    block_USART_IT_F302R8_03.ng     = 0;
    block_USART_IT_F302R8_03.nz     = 0;
    block_USART_IT_F302R8_03.noz    = 0;
    block_USART_IT_F302R8_03.nrpar  = 0;
    block_USART_IT_F302R8_03.nopar  = 1;
    block_USART_IT_F302R8_03.nipar  = 0;
    block_USART_IT_F302R8_03.nin    = 0;
    block_USART_IT_F302R8_03.nout   = 1;
    block_USART_IT_F302R8_03.nevout = 0;
    block_USART_IT_F302R8_03.nmode  = 0;
    block_USART_IT_F302R8_03.evout = NULL;
    block_USART_IT_F302R8_03.inptr  = inptr;
    block_USART_IT_F302R8_03.insz = NULL;
    block_USART_IT_F302R8_03.outptr = outptr;
    block_USART_IT_F302R8_03.outptr[0] = USART_IT_F302R8_03_block_outtbptr[0];
    block_USART_IT_F302R8_03.outsz = outszptr;
    block_USART_IT_F302R8_03.outsz[0]  = 1;
    block_USART_IT_F302R8_03.outsz[1]  = 1;
    block_USART_IT_F302R8_03.outsz[2]  = SCSREAL_N;
    block_USART_IT_F302R8_03.z = &(z[0]);
    if ((block_USART_IT_F302R8_03.oparptr = malloc(sizeof(void *)*block_USART_IT_F302R8_03.nopar))== NULL ) return 0;
    if ((block_USART_IT_F302R8_03.oparsz  = malloc(2*sizeof(int)*block_USART_IT_F302R8_03.nopar))== NULL ) return 0;
    if ((block_USART_IT_F302R8_03.opartyp = malloc(sizeof(int)*block_USART_IT_F302R8_03.nopar))== NULL ) return 0;
    block_USART_IT_F302R8_03.oparptr[0]   = (void *) OPAR_1;
    block_USART_IT_F302R8_03.oparsz[0]    = 1;
    block_USART_IT_F302R8_03.oparsz[1]    = 1;
    block_USART_IT_F302R8_03.opartyp[0]   = SCSREAL_N;
    block_USART_IT_F302R8_03.work = (void **)(((double *)work)+2);
  }
  cstblk4_m(&block_USART_IT_F302R8_03,4);
  {
    free(block_USART_IT_F302R8_03.oparptr);
    free(block_USART_IT_F302R8_03.oparsz);
    free(block_USART_IT_F302R8_03.opartyp);
  }

    /* Initial blocks must be called with flag 1 */
    /* Call of 'cstblk4_m' (type 4 - blk nb 3 - uid ) */
    { 
      /* set blk struc. of 'cstblk4_m' (type 4 - blk nb 3 - uid ) */
      block_USART_IT_F302R8_03.type   = 4;
      block_USART_IT_F302R8_03.ztyp   = 0;
      block_USART_IT_F302R8_03.ng     = 0;
      block_USART_IT_F302R8_03.nz     = 0;
      block_USART_IT_F302R8_03.noz    = 0;
      block_USART_IT_F302R8_03.nrpar  = 0;
      block_USART_IT_F302R8_03.nopar  = 1;
      block_USART_IT_F302R8_03.nipar  = 0;
      block_USART_IT_F302R8_03.nin    = 0;
      block_USART_IT_F302R8_03.nout   = 1;
      block_USART_IT_F302R8_03.nevout = 0;
      block_USART_IT_F302R8_03.nmode  = 0;
      block_USART_IT_F302R8_03.evout = NULL;
      block_USART_IT_F302R8_03.inptr  = inptr;
      block_USART_IT_F302R8_03.insz = NULL;
      block_USART_IT_F302R8_03.outptr = outptr;
      block_USART_IT_F302R8_03.outptr[0] = USART_IT_F302R8_03_block_outtbptr[0];
      block_USART_IT_F302R8_03.outsz = outszptr;
      block_USART_IT_F302R8_03.outsz[0]  = 1;
      block_USART_IT_F302R8_03.outsz[1]  = 1;
      block_USART_IT_F302R8_03.outsz[2]  = SCSREAL_N;
      block_USART_IT_F302R8_03.z = &(z[0]);
      if ((block_USART_IT_F302R8_03.oparptr = malloc(sizeof(void *)*block_USART_IT_F302R8_03.nopar))== NULL ) return 0;
      if ((block_USART_IT_F302R8_03.oparsz  = malloc(2*sizeof(int)*block_USART_IT_F302R8_03.nopar))== NULL ) return 0;
      if ((block_USART_IT_F302R8_03.opartyp = malloc(sizeof(int)*block_USART_IT_F302R8_03.nopar))== NULL ) return 0;
      block_USART_IT_F302R8_03.oparptr[0]   = (void *) OPAR_1;
      block_USART_IT_F302R8_03.oparsz[0]    = 1;
      block_USART_IT_F302R8_03.oparsz[1]    = 1;
      block_USART_IT_F302R8_03.opartyp[0]   = SCSREAL_N;
      block_USART_IT_F302R8_03.work = (void **)(((double *)work)+2);
    }
    cstblk4_m(&block_USART_IT_F302R8_03,1);
    cstblk4_m(&block_USART_IT_F302R8_03,2);
    {
      free(block_USART_IT_F302R8_03.oparptr);
      free(block_USART_IT_F302R8_03.oparsz);
      free(block_USART_IT_F302R8_03.opartyp);
    }

    /* Call of 'convert' (type 4 - blk nb 2 - uid ) */
    { 
      /* set blk struc. of 'convert' (type 4 - blk nb 2 - uid ) */
      block_USART_IT_F302R8_03.type   = 4;
      block_USART_IT_F302R8_03.ztyp   = 0;
      block_USART_IT_F302R8_03.ng     = 0;
      block_USART_IT_F302R8_03.nz     = 0;
      block_USART_IT_F302R8_03.noz    = 0;
      block_USART_IT_F302R8_03.nrpar  = 0;
      block_USART_IT_F302R8_03.nopar  = 0;
      block_USART_IT_F302R8_03.nipar  = 1;
      block_USART_IT_F302R8_03.nin    = 1;
      block_USART_IT_F302R8_03.nout   = 1;
      block_USART_IT_F302R8_03.nevout = 0;
      block_USART_IT_F302R8_03.nmode  = 0;
      block_USART_IT_F302R8_03.evout = NULL;
      block_USART_IT_F302R8_03.inptr  = inptr;
      block_USART_IT_F302R8_03.inptr[0]  = USART_IT_F302R8_03_block_outtbptr[0];
      block_USART_IT_F302R8_03.insz = inszptr;
      block_USART_IT_F302R8_03.insz[0]   = 1;
      block_USART_IT_F302R8_03.insz[1]   = 1;
      block_USART_IT_F302R8_03.insz[2]   = SCSREAL_N;
      block_USART_IT_F302R8_03.outptr = outptr;
      block_USART_IT_F302R8_03.outptr[0] = USART_IT_F302R8_03_block_outtbptr[1];
      block_USART_IT_F302R8_03.outsz = outszptr;
      block_USART_IT_F302R8_03.outsz[0]  = 1;
      block_USART_IT_F302R8_03.outsz[1]  = 1;
      block_USART_IT_F302R8_03.outsz[2]  = SCSUINT16_N;
      block_USART_IT_F302R8_03.z = &(z[0]);
      block_USART_IT_F302R8_03.ipar=(int*) &(IPAR1[0]);
      block_USART_IT_F302R8_03.work = (void **)(((double *)work)+1);
    }
    convert(&block_USART_IT_F302R8_03,1);
    convert(&block_USART_IT_F302R8_03,2);


    /* Dumy variable not used in embedded word but necessary for current version based on PC scicos C functions*/
    /* local_flag set to output update */
    local_flag = 1;
    double t; //Simulation time (not used)
return(1);
} //End of function USART_IT_F302R8_03_Initialize()
/*------------------------------  Step1 function called every 1 solver loop(s)*/
void USART_IT_F302R8_03_Step1()
{
  // double t;
  int nevprt=1;
  // int local_flag = 1; //Output update
  int nport;

/*---------------continuous activation state */
/*---------------STM32 block(s) without activation state  */
/*---------------STM32 solver step: NoEvt NoIn NoOut*/
/*---------------STM32 solver step: NoEvt NoIn Out*/
/*---------------STM32 solver step: NoEvt In Out*/
/*---------------STM32 solver step: NoEvt In NoOut*/
/*---------------FLAG: 1  */

  } //End of USART_IT_F302R8_03_Step1 function


double get_scicos_time()
{
  return sci_time;
}

void set_scicos_time(double t)
{
 sci_time = t;
}

int get_phase_simulation()
{
  return 1;
}



void set_block_error(int err)
{
  return;
}

void * scicos_malloc(size_t size)
{
  return malloc(size);
}

void scicos_free(void *p)
{
  free(p);
}

void do_cold_restart()
{
  return;
}

void sciprint (char *fmt)
{
  return;
}

